services:
  knockbox:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${KNOCKBOX_USER_SECRETS_DIR}:/home/app/.microsoft/usersecrets:ro
      - ${KNOCKBOX_USER_SECRETS_DIR}:/root/.microsoft/usersecrets:ro
      - ${KNOCKBOX_HTTPS_DIR}:/home/app/.aspnet/https:ro
      - ${KNOCKBOX_HTTPS_DIR}:/root/.aspnet/https:ro