services:
  knockbox:
    image: ${DOCKER_REGISTRY-}knockbox
    build:
      context: .
      dockerfile: host/KnockBox/Dockerfile
    volumes:
      - knockbox-data:/app/data

volumes:
  knockbox-data:
