services:
  knockbox:
    image: ${DOCKER_REGISTRY-}knockbox
    build:
      context: .
      dockerfile: host/KnockBox/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - knockbox-data:/app/data

volumes:
  knockbox-data:
