using System.Collections.Generic;
using KnockBox.Operator.Models;

namespace KnockBox.Operator.Services.Logic.FSM.ActionCommands;

/// <summary>
/// Defines a command generated by an Action Card to handle its own game logic,
/// reaction phases, and resolution.
/// </summary>
public interface IGameActionCommand
{
    /// <summary>
    /// Indicates if this command requires a reaction phase from target players.
    /// </summary>
    bool RequiresReaction { get; }

    /// <summary>
    /// Returns the IDs of the players who are targeted and must respond.
    /// </summary>
    IEnumerable<string> GetReactionTargetIds();

    /// <summary>
    /// Prepares the game state for the pending reaction (e.g., removing number cards from discard).
    /// </summary>
    void SetupPendingState();

    /// <summary>
    /// Executes the action logic when it resolves successfully (e.g., not blocked).
    /// </summary>
    void Execute();

    /// <summary>
    /// Handles logic when the action is blocked by a player's reaction (e.g., returning cards to hand).
    /// </summary>
    void OnBlocked();

    /// <summary>
    /// Updates the target of the command (used for redirection).
    /// </summary>
    void UpdateTarget(string newTargetId);

    /// <summary>
    /// The ID of the player who initiated the action.
    /// </summary>
    string InitiatorPlayerId { get; }

    /// <summary>
    /// The cards that were played to generate this command.
    /// </summary>
    IEnumerable<Card> PlayedCards { get; }

    /// <summary>
    /// The primary card being resolved (e.g., ActionCard or OperatorCard).
    /// </summary>
    Card? PrimaryCard { get; }
}
