using KnockBox.Core.Components.Shared;
using KnockBox.DndMapper.Services.State.Games;
using KnockBox.DndMapper.Services.State.Games.Data;
using Microsoft.AspNetCore.Components;

namespace KnockBox.DndMapper.Pages.Components
{
    /// <summary>
    /// Renders the read-only existing markup plus the interactive drawing surface
    /// for the markup overlay (v1.x §5.6). Stays inside <c>.dndm-canvas-transform</c>
    /// so the drawing surface rides the same pan/zoom as the map. The associated
    /// <see cref="Core.Components.Shared.SvgDrawingEngine"/> and toolbar are owned
    /// by <c>MapCanvas</c> and rendered outside the transform so the toolbar stays
    /// at viewport scale.
    /// </summary>
    public partial class MarkupOverlay : DisposableComponent
    {
        [Parameter, EditorRequired] public DndMapperGameState State { get; set; } = default!;
        [Parameter, EditorRequired] public Map Map { get; set; } = default!;

        /// <summary>
        /// Id of the <c>&lt;svg&gt;</c> the engine should bind to. Pre-generated by the
        /// parent so the engine and this overlay can share a stable id without an
        /// <c>@ref</c> round-trip.
        /// </summary>
        [Parameter, EditorRequired] public string SvgId { get; set; } = default!;

        /// <summary>
        /// When <c>false</c> the drawing surface is set to <c>pointer-events: none</c>
        /// so pan/zoom and token interactions fall through to layers beneath. Set by
        /// MapCanvas based on the host's markup toggle + space-held state.
        /// </summary>
        [Parameter] public bool IsActive { get; set; } = true;
    }
}
