namespace KnockBox.AlphaChain.Contracts;

/// <summary>Strongly-typed identity for every modifier card, replacing the legacy string ids.
/// The factory creates a card from one of these; the network/UI id surface is <c>ToString()</c>.</summary>
public enum ModifierId
{
    Unknown = 0,
    TheAnchor,
    Vanilla,
    ConsonantCrunch,
    VocalVowels,
    VowelSurge,
    TheArchitect,
    BrickLayer,
    Speedracer,
    LetterHoarder,
    Sesquipedalian,
    GutturalRoar,
    HighRoller,
    PerfectLink,
    TheVault,
    Redline,
    PanicButton,
    HyperDrive,
    TaxCollector,
    IrsAgent,
    RouletteWheel,
    TollBooth,
    BaitAndSwitch,
    Blindfold,
    DoubleDown,
    AnchorChain,
    FlakCannon,
    BountyHunter,
    TitaniumMirror,
    HeatSink,
    Prism,
    Wildcard,
    Catalyst,
    TheBlueprint,
    SlowBurn,
    TryHard,
    ChronoSyphon,
    Forgery,
    TaxWriteOff,
    BoosterPack,
    Scavenger,
    MagnifyingGlass,
}
